m_dict_technical = {
    'Ada': ['ada'],
    'ASP.Net': ['asp.net', 'asp net', 'aspnet'],
    'Angular JS' : ['angular js', 'angularjs'],
    'Bash': ['bash'],
    'Basic': ['basic'],
    'C': ['c'],
    'C++': ['c++', 'c ++'],
    'C#': ['c #', 'c#'],
    'Caml': ['caml'],
    'CSS': ['css'],
    'CoffeeScript': ['coffeescript'],
    'Cobol': ['cobol'],
    'Dupal' : ['drupal'],
    'Erlang': ['erlang'],
    'Express JS' : ['expressjs', 'express js'],
    'Fortran': ['fortran'],
    'Go': ['go!', 'golang', 'go lang'],
    'Git' : ['git', 'github'],
    'Mercurial' : ['mercurial'],
    'Haskell': ['haskell'],
    'HTML': ['html'],
    'Java': ['java'],
    'JavaScript': ['javascript', 'java script'],
    'JSON': ['json'],
    'Julia': ['julia'],
    'Kotlin': ['kotlin'],
    'LaTeX': ['latex'],
    'Lisp': ['lisp'],
    'Lua': ['lua'],
    'MATLAB': ['matlab'],
    'Node.Js': ['node.js', 'node js', 'nodejs'],
    'Octave': ['octave'],
    'Objective-C': ['objective c', 'objectivec', 'objective-c'],
    'OCaml': ['ocaml'],
    'Pascal': ['pascal'],
    'Perl': ['perl'],
    'Perl 6': ['perl 6', 'perl6'],
    'PHP': ['php'],
    'PostScript': ['postscript'],
    'Python': ['python', 'python2', 'python 2', 'python3', 'python 3'],
    'R': ['r', 'rprogramming', 'r programming'],
    'React JS': ['reactjs', 'react js', 'react.js'],
    'Ruby': ['ruby'],
    'Rust': ['rust'],
    'Scala': ['scala'],
    'Shell': ['shell'],
    'Swift': ['swift'],
    'TypeScript': ['typescript', 'type script'],
    'Visual Basic': ['visual basic', 'visualbasic'],
    'Visual basic .NET': ['visual basic .net', 'visual basic net', 'visualbasic net'],
    'Oracle RDBMS': ['oracle rdbms', 'oraclerdbms'],
    'IBM DB2': ['ibm db2', 'ibmdb2'],
    'Scikit-Learn' :['scikit-learn', 'sklearn', 'scikit learn'],
    'SQL Server': ['sql server', 'sqlserver'],
    'SAP Sybase ASE': ['sap sybase ase'],
    'Teradata': ['teradata'],
    'MYSQL': ['mysql', 'my sql'],
    'Microsoft Access': ['microsoft access', 'microsoftaccess'],
    'SQLite': ['sqlite'],
    'PostgreSQL': ['postgresql', 'postgre sql'],
    'Amazon RDS': ['amazon rds', 'amazonrds'],
    'MongoDB': ['mongodb', 'mongo db'],
    'Redis': ['redis'],
    'CouchDB': ['couchdb', 'couch db'],
    'Neo4j': ['neo4j'],
    'Couchbase': ['couchbase'],
    'Hadoop HDFS': ['hadoop hdfs', 'hadoopdbfs'],
    'MariaDB': ['maria db', 'mariadb'],
    'Elasticsearch': ['elasticsearch', 'elastic search'],
    'Cassandra': ['cassandra'],
    'Terradata': ['terradata'],
    'Hive': ['hive'],
    'SAP HANA': ['sap hana', 'saphana'],
    'Amazon DynamoDB': ['dynamodb', 'dynamo db'],
    'Azure SQL Database': ['azure sql database', 'azure sql'],
    'Google BigQuery': ['google bigquery', 'google big query'],
    'Wordpress' :['wordpress', 'word press'],
}

m_dict_edu_degrees = {
    'Master': ['masters','master', 'm sc', 'm.sc', 'msc', 'm tech',
               'm.tech', 'mtech', 'mca', 'm c a', 'm.c.a',
               'm.s', 'm.b.a', 'mba', 'm.com', 'mcom', 'mca', 'm.c.a'],
    'Bachelor': ['bachelors','bachelor', 'b.a', 'bca', 'b.c.a', 'bba', 'b.b.a',
                 'bcom', 'b.com', 'b.e', 'be', 'b.eng', 'beng', 'b.tech', 'btech'],
    'Doctorate': ['doctorate in', 'phd', 'p hd', 'p.hd'],
}

m_dict_edu_field_study  = {
    'Computer Science': ['computer science', 'computerscience'],
    'Electrical Engineering': ['electrical engineering', 'electricalengineering'],
    'Information Technology': ['information technology', 'informationtechnology'],
    'Computer Applications' : ['computer applications', 'computerapplications'],
    'Electronics and Communications Engineering' : ['electronics and communications engineering'],
    'Mechanical Engineering' : ['mechanical engineering', 'mechanicalengineering']
}


selectors_required_skills = ['deep knowledge', 'deep understanding',
                             'good understanding', 'must have', 'good knowledge',
                             'in depth knowledge', 'must have skills',
                             'expert knowledge', 'strong understanding',
                             'strong in', 'strong grasp']


